src/main/java/nenad/centilitest/dto/BaseDTO.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nenad.centilitest.dto;

/**
 * DataTransferObject with default fields
 *
 * @author nenad <barugdzicnenad@gmail.com>
 */
public class BaseDTO {

    protected boolean failed;

    public boolean isFailed() {
        return failed;
    }

    public void setFailed(boolean failed) {
        this.failed = failed;
    }
}

src/main/java/nenad/centilitest/dto/DocumentDTO.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nenad.centilitest.dto;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * DataTransferObject representing document
 *
 * @author nenad <barugdzicnenad@gmail.com>
 */
@XmlRootElement(name = "documentDTO")
@XmlAccessorType(XmlAccessType.FIELD)
public class DocumentDTO extends BaseDTO implements Serializable {

    private static final long serialVersionUID = 1L;
    private Long id;
    private String code;
    private Date date;
    private String name;
    private List<DocumentItemDTO> items;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<DocumentItemDTO> getItems() {
        return items;
    }

    public void setItems(List<DocumentItemDTO> items) {
        this.items = items;
    }

}

src/main/java/nenad/centilitest/dto/DocumentItemDTO.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nenad.centilitest.dto;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * DataTransferObject representing item
 *
 * @author nenad <barugdzicnenad@gmail.com>
 */
@XmlRootElement(name = "itemDTO")
@XmlAccessorType(XmlAccessType.FIELD)
public class DocumentItemDTO extends BaseDTO implements Serializable {

    private static final long serialVersionUID = 1L;
    private Long id;
    private String name;
    private double price;
    private Long id_document;
    private String docCode;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public Long getId_document() {
        return id_document;
    }

    public void setId_document(Long id_document) {
        this.id_document = id_document;
    }

    public String getDocCode() {
        return docCode;
    }

    public void setDocCode(String docCode) {
        this.docCode = docCode;
    }

}

src/main/java/nenad/centilitest/dto/DocumentItemListDTO.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nenad.centilitest.dto;

import java.io.Serializable;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * DataTransferObject representing list of items
 *
 * @author nenad <barugdzicnenad@gmail.com>
 */
@XmlRootElement(name = "itemsDTO")
@XmlAccessorType(XmlAccessType.FIELD)
public class DocumentItemListDTO extends BaseDTO implements Serializable {

    private static final long serialVersionUID = 1L;
    @XmlElement(name = "itemDTO")
    private List<DocumentItemDTO> items = null;

    public List<DocumentItemDTO> getItems() {
        return items;
    }

    public void setItems(List<DocumentItemDTO> items) {
        this.items = items;
    }

}

src/main/java/nenad/centilitest/common/LoggableBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nenad.centilitest.common;

import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

/**
 * Helping class for logging and redirecting
 *
 * @author nenad <barugdzicnenad@gmail.com>
 */
public class LoggableBean {

    public static final String LOG_MESSAGE = "An error has been occured while ";
    /**
     * Method for printing log
     *
     * @param isError state of method execution
     * @param methodName name of method called
     * @param param list of parameters in method
     */
    public void printLog(boolean isError, String methodName, String param) {
        ExternalContext eCtx = FacesContext.getCurrentInstance().getExternalContext();
        HttpServletRequest request = (HttpServletRequest) eCtx.getRequest();
        String contextName = request.getContextPath().substring(1);// da izbacimo prvi slash
        String status = isError ? "ROLLBACK" : "COMMIT";
        String sessionId = request.getSession().getId();
        int lenth = 0;
        Date beginAndEndTime = Calendar.getInstance().getTime();

        String requestParamsJSON = "";
        if (param != null) {
            requestParamsJSON += "{" + "\"params\"::\"" + param + "\"}";
        }
        String log = String.format("%1$s;[%2$s];<%3$s>;%4$d;%5$tY-%5$tm-%5$tdT%5$tH:%5$tM:%5$tS.%5$tL%5$tZ;%6$tY-%6$tm-%6$tdT%6$tH:%6$tM:%6$tS.%6$tL%6$tZ;%7$s;%8$s;", contextName, methodName, status, lenth, beginAndEndTime, beginAndEndTime, sessionId, requestParamsJSON);
        Logger logg = Logger.getLogger(this.getClass().getName());
        logg.info(log);
    }

    /**
     * Method for redirecting on another page
     *
     * @param path path of URL of wanted page
     * @throws java.lang.Exception
     */
    public void updateClick(String path) throws IOException {
        ExternalContext eCtx = FacesContext.getCurrentInstance().getExternalContext();
        HttpServletRequest request = (HttpServletRequest) eCtx.getRequest();
        try {
            eCtx.redirect(request.getContextPath() + path);
        } catch (IOException ex) {
            Logger.getLogger(LoggableBean.class.getName()).log(Level.SEVERE, " Eroor on redirecting on page: " + path, ex);
            throw ex;
        }
    }

}

src/main/java/nenad/centilitest/controller/DocumentsAndItemsController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nenad.centilitest.controller;

import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import nenad.centilitest.client.DocumentItemRestClient;
import nenad.centilitest.client.DocumentRestClient;
import nenad.centilitest.common.LoggableBean;
import nenad.centilitest.dto.DocumentDTO;
import nenad.centilitest.dto.DocumentItemDTO;
import nenad.centilitest.dto.DocumentItemListDTO;
import nenad.centilitest.dto.DocumentListDTO;

/**
 * Bean for managing JSF page index
 *
 * @author nenad <barugdzicnenad@gmail.com>
 */
@ApplicationScoped
@ManagedBean(name = "docBean")
public class DocumentsAndItemsController extends LoggableBean {

    private DocumentListDTO documentList;
    private boolean docForm;
    private boolean itemForm;
    private DocumentDTO selectedDoc;
    private DocumentItemDTO selectedItem;
    private DocumentItemListDTO allItems;

    /**
     * Getting list of all documents for data table with id=docTable
     *
     * @return DocumentListDTO entity with a list of documents
     */
    public DocumentListDTO getDocumentList() {
        if (documentList == null || documentList.getDocuments() == null) {
            try {
                DocumentRestClient client = new DocumentRestClient();
                documentList = client.findAll(DocumentListDTO.class);
                client.close();
                if (documentList.isFailed()) {
                    FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, LOG_MESSAGE + "getting all documents!", null);
                    FacesContext.getCurrentInstance().addMessage("Error", message);
                    printLog(true, "getDocumentList", "");
                }
            } catch (Exception e) {
                FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, e.getMessage(), null);
                FacesContext.getCurrentInstance().addMessage("Error", message);
                Logger.getLogger(DocumentsAndItemsController.class.getName()).log(Level.SEVERE, " getDocumentList: ", e);
                printLog(true, "getDocumentList", e.getMessage());
            }
        }
        return documentList;
    }

    public void setDocumentList(DocumentListDTO documentList) {
        this.documentList = documentList;
    }

    /**
     * Removing selected item in table with id=itemTable from table
     * document_items in database, then from all lists where that object was
     * putted
     *
     */
    public void removeItemClick() {
        try {
            if (getSelectedItem() == null) {
                FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "You must select item", null);
                FacesContext.getCurrentInstance().addMessage("Info", message);
            } else {
                if (getSelectedDoc() == null || !Objects.equals(getSelectedDoc().getId(), getSelectedItem().getId_document())) {
                    DocumentRestClient client = new DocumentRestClient();
                    DocumentDTO temp = client.findDocument(DocumentDTO.class, String.valueOf(getSelectedItem().getId_document()));
                    if (temp.isFailed()) {
                        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, LOG_MESSAGE + "finding document for item ", null);
                        FacesContext.getCurrentInstance().addMessage("Error", message);
                        printLog(true, "removeItemClick", "id_document: " + getSelectedItem().getId_document());
                        client.close();
                        return;
                    }
                    setSelectedDoc(temp);
                }
                DocumentItemRestClient client = new DocumentItemRestClient();
                int status = client.remove(String.valueOf(getSelectedItem().getId()));
                client.close();
                if (status < 400) {
                    int tempIdx = 0;
                    for (int i = 0; i < getSelectedDoc().getItems().size(); i++) {
                        if (Objects.equals(getSelectedDoc().getItems().get(i).getId(), getSelectedItem().getId())) {
                            tempIdx = i;
                            break;
                        }
                    }
                    getSelectedDoc().getItems().remove(tempIdx);
                    for (int i = 0; i < getAllItems().getItems().size(); i++) {
                        if (Objects.equals(getAllItems().getItems().get(i).getId(), getSelectedItem().getId())) {
                            tempIdx = i;
                            break;
                        }
                    }
                    getAllItems().getItems().remove(tempIdx);
                    printLog(false, "removeItemClick", null);
                } else {
                    FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, LOG_MESSAGE + "deleting items: " + status, null);
                    FacesContext.getCurrentInstance().addMessage("Error", message);
                    printLog(true, "removeItemClick", "status = " + status);
                }
            }
        } catch (Exception e) {
            setAllItems(null);
            setSelectedDoc(null);
            setSelectedItem(null);
            FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, e.getMessage(), null);
            FacesContext.getCurrentInstance().addMessage("Error", message);
            Logger.getLogger(DocumentsAndItemsController.class.getName()).log(Level.SEVERE, " removeItemClick: ", e);
            printLog(true, "removeItemClick", e.getMessage());
        }
    }

    /**
     * Removing selected document in table id=docTable from table documents in
     * database, then from all lists where that object was putted
     *
     */
    public void removeDocClick() {
        try {
            if (getSelectedDoc() == null) {
                FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "You must select document", null);
                FacesContext.getCurrentInstance().addMessage("Info", message);
            } else {
                DocumentRestClient client = new DocumentRestClient();
                int status = client.remove(String.valueOf(getSelectedDoc().getId()));
                client.close();
                if (status < 400) {
                    getDocumentList().getDocuments().remove(getSelectedDoc());
                    printLog(false, "removeDocClick", null);
                    setSelectedDoc(null);
                    setSelectedItem(null);
                    setAllItems(null);
                } else {
                    FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, LOG_MESSAGE + "deleting documentwith with error: " + status, null);
                    FacesContext.getCurrentInstance().addMessage("Error", message);
                    printLog(true, "removeDocClick", "status = " + status);
                }
            }
        } catch (Exception e) {
            setDocumentList(null);
            setAllItems(null);
            setSelectedDoc(null);
            setSelectedItem(null);
            FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, e.getMessage(), null);
            FacesContext.getCurrentInstance().addMessage("Error", message);
            Logger.getLogger(DocumentsAndItemsController.class.getName()).log(Level.SEVERE, " removeDocClick: ", e);
            printLog(true, "removeDocClick", e.getMessage());
        }
    }

    public boolean getDocForm() {
        return docForm;
    }

    public void setDocForm(boolean docForm) {
        this.docForm = docForm;
    }

    public boolean getItemForm() {
        return itemForm;
    }

    public void setItemForm(boolean itemForm) {
        this.itemForm = itemForm;
    }

    /**
     * Methods to check whether selected document has or has not items
     *
     * @return true if selected document has item, false if has not
     */
    public boolean getHasItems() {
        return getSelectedDoc() != null && getSelectedDoc().getItems() != null && !getSelectedDoc().getItems().isEmpty();
    }

    /**
     * Opening list of items if selected document has items
     *
     */
    public void onRowSelect() {
        try {
            if (getSelectedDoc() == null) {
                FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "You must select document", null);
                FacesContext.getCurrentInstance().addMessage("Info", message);
            } else {
                if (getSelectedDoc().getItems() == null || getSelectedDoc().getItems().isEmpty()) {
                    DocumentItemRestClient client = new DocumentItemRestClient();
                    DocumentItemListDTO list = client.findAllDocumentItemsByDocument(DocumentItemListDTO.class, String.valueOf(getSelectedDoc().getId()));
                    client.close();
                    if (list.isFailed()) {
                        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, LOG_MESSAGE + "getting items for document", null);
                        FacesContext.getCurrentInstance().addMessage("Error", message);
                        Logger.getLogger(DocumentsAndItemsController.class.getName()).log(Level.SEVERE, " An error has been occured while getting items for document");
                        printLog(true, "onRowSelect", null);

src/main/webapp/index.xhtml
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <f:view contentType="text/html">
        <h:head>
            <link rel="stylesheet" href="./assets/css/main.css" type="text/css"/>
            <title>Centili candidate project</title>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="shortcut icon" href="./images/centiliTitleLogo.png" type="image/jpg"/>

        </h:head>
        <h:body id="top">

            <!-- Banner -->
            <!--
                    To use a video as your background, set data-video to the name of your video without
                    its extension (eg. images/banner). Your video must be available in both .mp4 and .webm
                    formats to work correctly.
            -->
            <section id="banner" data-video="./images/banner">
                <div class="inner">
                    <header>
                        <h1>Centili candidate project</h1>
                        <p>Project request by company <a href="https://www.centili.com/">Centili</a> for a candidate who has applied for a job.<br/>
                            You can create your own documents and items for that documents, and manage them as you want.<br/>
                            I hope you will like what I did.<br/>
                            King regards,<br/>
                            <a href="https://www.linkedin.com/in/nenad-barugdzic-705512b2">Nenad</a>
                        </p>
                    </header>
                    <a href="#main" class="more">Learn More</a>
                </div>
            </section>

            <!-- Main -->
            <div id="main">
                <div class="inner">

                    <!-- Boxes -->
                    <div class="thumbnails">
                        <h:form id="form">
                            <p:growl id="msgs" showDetail="true" />
                            <p:panel header="Documents" id="docPanel">
                                <p:growl id="docMsg" showDetail="true" />
                                <p:commandButton value="Add documents" action="#{addBean.addDocumentClick}" styleClass="buttonStyle" update=":form"/>
                                <br/>
                                <p:dataTable var="doc" value="#{docBean.documentList.documents}" rows="10" id="docTable"
                                             paginator="true"
                                             paginatorAlwaysVisible="false"
                                             paginatorPosition="top"
                                             rowsPerPageTemplate="5,10,20"
                                             selectionMode="single" 
                                             class=""
                                             selection="#{docBean.selectedDoc}"
                                             rowKey="#{doc.id}">

                                    <p:column headerText="Code" sortBy="#{doc.code}" filterBy="#{doc.code}">
                                        <h:outputText value="#{doc.code}"  title="#{doc.code}"/>
                                    </p:column>

                                    <p:column headerText="Name"  sortBy="#{doc.name}" filterBy="#{doc.name}">
                                        <h:outputText value="#{doc.name}"  title="#{doc.name}"/>
                                    </p:column>

                                    <p:column headerText="Date"  sortBy="#{doc.date}" filterBy="#{doc.date}">
                                        <h:outputText value="#{doc.date}" >
                                            <f:convertDateTime pattern="dd.MM.yyyy."/>
                                        </h:outputText>
                                    </p:column>

                                    <f:facet name="footer">
                                        <p:commandButton process="docTable" update=":form" icon="ui-icon-search" value="Delete" oncomplete="PF('deleteDoc').show()" />
                                        <p:commandButton process="docTable" icon="ui-icon-search" value="Edit"  action="#{addBean.editDocClick}" update=":form"/>
                                        <p:commandButton process="docTable" icon="ui-icon-search" value="Add item" action="#{addBean.addItemClick}" update=":form"/>
                                        <p:commandButton process="docTable" icon="ui-icon-search" value="View" action="#{docBean.onRowSelect}" update=":form"/>

                                    </f:facet>
                                </p:dataTable>
                            </p:panel>
                            <p:panel header="Items" id="itemsPanel" style="margin-top: 50px">
                                <p:growl id="itmsPanel" showDetail="true" />
                                <p:commandButton process="docTable" update=":form" icon="ui-icon-search" value="Show all items" oncomplete="PF('allItems').show()" />
                                <p:commandButton value="Add item" action="#{addBean.addItemClick}" styleClass="buttonStyle" rendered="#{docBean.hasItems}" update=":form"/>
                                <p:dataTable var="item" value="#{docBean.selectedDoc.items}" rows="10" id="itemTable"
                                             paginator="true"
                                             rendered="#{docBean.hasItems}"
                                             paginatorAlwaysVisible="false"
                                             selectionMode="single" 
                                             paginatorPosition="top"
                                             rowsPerPageTemplate="5,10,20"
                                             selection="#{docBean.selectedItem}"
                                             rowKey="#{item.id}">
                                    <f:facet name="header">
                                        <h:outputText value="Document: #{docBean.selectedDoc.name} - #{docBean.selectedDoc.code}"/>
                                    </f:facet>
                                    <p:column headerText="Name"  sortBy="#{item.name}" filterBy="#{item.name}">
                                        <h:outputText value="#{item.name}" title="#{item.name}"/>
                                    </p:column>

                                    <p:column headerText="Code" sortBy="#{item.price}" filterBy="#{item.price}">
                                        <h:outputText value="#{item.price}">
                                        </h:outputText>
                                    </p:column>

                                    <f:facet name="footer">
                                        <p:commandButton process="itemTable" update=":form" icon="ui-icon-search" value="Delete" oncomplete="PF('deleteItem').show()" />
                                        <p:commandButton process="itemTable" icon="ui-icon-search" value="Edit"  action="#{addBean.editItemClick}" update=":form"/>
                                    </f:facet>
                                </p:dataTable>
                            </p:panel>

                            <p:dialog header="Are you shure you want to delete document?" widgetVar="deleteDoc" modal="true" showEffect="fade" hideEffect="fade" resizable="false" id="dialogDoc">
                                <p:outputPanel id="docDetail" style="text-align:center;">
                                    <h:outputText value="#{docBean.docDeleteMessage}"/>
                                    <p:panelGrid  columns="2" rendered="#{docBean.selectedDoc != null}" >
                                        <p:commandButton action="#{docBean.removeDocClick}" value="Yes" update="form" oncomplete="PF('deleteDoc').hide()"/>                     
                                        <p:commandButton type="button" value="No" onclick="PF('deleteDoc').hide()"/>
                                    </p:panelGrid>
                                </p:outputPanel>
                            </p:dialog>

                            <p:dialog header="Are you shure you want to delete item?" widgetVar="deleteItem" modal="true" showEffect="fade" hideEffect="fade" resizable="false" id="dialogItem">
                                <p:outputPanel id="itemDetail" style="text-align:center;">
                                    <h:outputText value="#{docBean.itemDeleteMessage}"/>
                                    <p:panelGrid  columns="2" rendered="#{docBean.selectedItem  != null}">
                                        <p:commandButton action="#{docBean.removeItemClick}" value="Yes" update="form" oncomplete="PF('deleteItem').hide()"/>                     
                                        <p:commandButton type="button" value="No" onclick="PF('deleteItem').hide()"/>
                                    </p:panelGrid>
                                </p:outputPanel>
                            </p:dialog>
                            <p:dialog header="All items" widgetVar="allItems" modal="true" showEffect="fade" hideEffect="fade" resizable="false" width="80%">
                                <p:dataTable var="item" value="#{docBean.allItems.items}" rows="10" id="allItemTable"
                                             paginator="true"
                                             selectionMode="single" 
                                             paginatorPosition="top"
                                             rowsPerPageTemplate="5,10,20"
                                             selection="#{docBean.selectedItem}"
                                             rowKey="#{item.id}">>

                                    <p:column headerText="Name"  sortBy="#{item.name}" filterBy="#{item.name}">
                                        <h:outputText value="#{item.name}" title="#{item.name}"/>
                                    </p:column>

                                    <p:column headerText="Code" sortBy="#{item.price}" filterBy="#{item.price}">
                                        <h:outputText value="#{item.price}">
                                        </h:outputText>
                                    </p:column>

                                    <p:column headerText="Document code" sortBy="#{item.docCode}" filterBy="#{item.docCode}">
                                        <h:outputText value="#{item.docCode}" title="#{item.docCode}"/>
                                    </p:column>
                                    <f:facet name="footer">
                                        <p:commandButton process="allItemTable" update=":form" icon="ui-icon-search" value="Delete" oncomplete="PF('deleteItem').show()" />
                                        <p:commandButton process="allItemTable" icon="ui-icon-search" value="Edit"  action="#{addBean.editItemClick}" update=":form"/>
                                    </f:facet>
                                </p:dataTable>
                            </p:dialog>
                        </h:form>
                    </div>

                </div>
            </div>

            <!-- Footer -->
            <footer id="footer">
                <div class="inner">
                    <ul class="icons">
                        <li><a href="https://www.linkedin.com/in/nenad-barugdzic-705512b2" class="icon fa-linkedin"><span class="label">Linkedin</span></a></li>
                        <li><a href="https://twitter.com/dzobica" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
                        <li><a href="https://www.instagram.com/nbarugdzic/" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
                        <li><a href="https://plus.google.com/+NenadBarugdzic" class="icon fa-envelope"><span class="label">GMAIL</span></a></li>
                    </ul>
                    <p class="copyright"> Design: <a href="https://templated.co">TEMPLATED</a>. Videos: <a href="https://www.centili.com/">Centili</a>.</p>
                </div>
            </footer>

            <!-- Scripts -->
            <script src="./assets/js/jquery.scrolly.min.js"></script>
            <script src="./assets/js/skel.min.js"></script>
            <script src="./assets/js/util.js"></script>
            <script src="./assets/js/main.js"></script>

        </h:body>
    </f:view>
</html>